#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Animal
  # forward declarations
  class Human < ::ProtocolBuffers::Message; end

  class Human < ::ProtocolBuffers::Message
    set_fully_qualified_name "animal.Human"

    optional :string, :first_name, 1
    repeated :string, :middle_names, 2
    optional :string, :last_name, 3
    optional ::Animal::Human, :mother, 4
    optional ::Animal::Human, :father, 5
    optional :string, :path, 6
    optional :string, :version, 7
    optional :string, :timestamp, 8
    optional :string, :email, 9
    optional :bool, :vegetarian, 10
    optional :int32, :age, 11
  end

end
