# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unicorn.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
 add_message "Unicorn" do
   optional :colour, :string, 1
   optional :horn_length, :int32, 2
   optional :last_seen, :int32, 3
   repeated :favourite_numbers, :int32, 4
 end
end

Unicorn = Google::Protobuf::DescriptorPool.generated_pool.lookup("Unicorn").msgclass