#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Animal
  # forward declarations
  class UnicornEvent < ::ProtocolBuffers::Message; end

  class UnicornEvent < ::ProtocolBuffers::Message
    set_fully_qualified_name "animal.UnicornEvent"

    optional :string, :colour, 1
    optional :int32, :horn_length, 2
    optional :int32, :last_seen, 3
    optional :string, :timestamp, 4
    optional :string, :host, 5
    optional :string, :path, 6
    optional :string, :version, 7
    optional :bool, :has_wings, 8
    
  end

end
