#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'header/header.pb'; rescue LoadError; end

module Logging
  # forward declarations
  class Event < ::ProtocolBuffers::Message; end

  class Event < ::ProtocolBuffers::Message
    set_fully_qualified_name "Logging.Event"

    optional :string, :name, 1
    optional ::Grpc::Header, :header, 2
  end

end
