# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foobar/akamai_siem/AkamaiSiem.proto

begin; require 'google/protobuf'; rescue LoadError; end

# TODO fix this: req ui re 'header/header_pb';
# TODO remove this:
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Header" do
    optional :unix_timestamp, :int64, 1
    optional :sender_id, :string, 2
  end
end

Header = Google::Protobuf::DescriptorPool.generated_pool.lookup("Header").msgclass


Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "foobar.akamai_siem.AkamaiSiemEvent" do
    optional :header, :message, 1, "Header"
    optional :version, :string, 2
    optional :connector_id, :string, 3
    optional :geo, :message, 4, "foobar.akamai_siem.AkamaiSiemGeo"
    optional :httpMessage, :message, 5, "foobar.akamai_siem.AkamaiSiemHttpMessage"
    optional :attackData, :message, 6, "foobar.akamai_siem.AkamaiSiemAttackData"
  end
  add_message "foobar.akamai_siem.AkamaiSiemHttpMessage" do
    optional :host, :string, 1
    optional :httpMethod, :string, 2
    optional :path, :string, 3
    optional :port, :uint32, 4
    optional :protocol, :string, 5
    optional :query, :string, 6
    optional :requestHeaders, :string, 7
    optional :requestId, :string, 8
    optional :tls, :string, 9
    optional :start, :string, 10
    optional :status, :uint32, 11
    optional :bytes, :uint32, 12
    optional :responseHeaders, :string, 13
  end
  add_message "foobar.akamai_siem.AkamaiSiemAttackData" do
    optional :clientIP, :string, 1
    optional :configId, :string, 2
    optional :policyId, :string, 3
    optional :ruleSelectors, :string, 4
    repeated :rules_translated, :message, 5, "foobar.akamai_siem.AkamaiSiemRule"
  end
  add_message "foobar.akamai_siem.AkamaiSiemRule" do
    optional :rule, :string, 1
    optional :ruleAction, :string, 2
    optional :ruleData, :string, 3
    optional :ruleMessage, :string, 4
    optional :ruleSelector, :string, 5
    optional :ruleTag, :string, 6
    optional :ruleVersion, :string, 7
  end
  add_message "foobar.akamai_siem.AkamaiSiemGeo" do
    optional :asn, :uint32, 1
    optional :city, :string, 2
    optional :continent, :string, 3
    optional :country, :string, 4
    optional :regionCode, :string, 5
  end
end

module Foobar
  module AkamaiSiem
    AkamaiSiemEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("foobar.akamai_siem.AkamaiSiemEvent").msgclass
    AkamaiSiemHttpMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("foobar.akamai_siem.AkamaiSiemHttpMessage").msgclass
    AkamaiSiemAttackData = Google::Protobuf::DescriptorPool.generated_pool.lookup("foobar.akamai_siem.AkamaiSiemAttackData").msgclass
    AkamaiSiemRule = Google::Protobuf::DescriptorPool.generated_pool.lookup("foobar.akamai_siem.AkamaiSiemRule").msgclass
    AkamaiSiemGeo = Google::Protobuf::DescriptorPool.generated_pool.lookup("foobar.akamai_siem.AkamaiSiemGeo").msgclass
  end
end
