# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dnsmessage.proto3

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "PBDNSMessage" do
    optional :type, :enum, 1, "PBDNSMessage.Type"
    optional :messageId, :bytes, 2
    optional :serverIdentity, :bytes, 3
    optional :socketFamily, :enum, 4, "PBDNSMessage.SocketFamily"
    optional :socketProtocol, :enum, 5, "PBDNSMessage.SocketProtocol"
    optional :from, :bytes, 6
    optional :to, :bytes, 7
    optional :inBytes, :uint64, 8
    optional :timeSec, :uint32, 9
    optional :timeUsec, :uint32, 10
    optional :id, :uint32, 11
    optional :question, :message, 12, "PBDNSMessage.DNSQuestion"
    optional :response, :message, 13, "PBDNSMessage.DNSResponse"
    optional :originalRequestorSubnet, :bytes, 14
    optional :requestorId, :string, 15
    optional :initialRequestId, :bytes, 16
    optional :deviceId, :bytes, 17
  end
  add_message "PBDNSMessage.DNSQuestion" do
    optional :qName, :string, 1
    optional :qType, :uint32, 2
    optional :qClass, :uint32, 3
  end
  add_message "PBDNSMessage.DNSResponse" do
    optional :rcode, :uint32, 1
    repeated :rrs, :message, 2, "PBDNSMessage.DNSResponse.DNSRR"
    optional :appliedPolicy, :string, 3
    repeated :tags, :string, 4
    optional :queryTimeSec, :uint32, 5
    optional :queryTimeUsec, :uint32, 6
    optional :appliedPolicyType, :enum, 7, "PBDNSMessage.PolicyType"
  end
  add_message "PBDNSMessage.DNSResponse.DNSRR" do
    optional :name, :string, 1
    optional :type, :uint32, 2
    optional :class, :uint32, 3
    optional :ttl, :uint32, 4
    optional :rdata, :bytes, 5
  end
  add_enum "PBDNSMessage.Type" do
    value :Dummy0, 0
    value :DNSQueryType, 1
    value :DNSResponseType, 2
    value :DNSOutgoingQueryType, 3
    value :DNSIncomingResponseType, 4
  end
  add_enum "PBDNSMessage.SocketFamily" do
    value :Dummy1, 0
    value :INET, 1
    value :INET6, 2
  end
  add_enum "PBDNSMessage.SocketProtocol" do
    value :Dummy2, 0
    value :UDP, 1
    value :TCP, 2
  end
  add_enum "PBDNSMessage.PolicyType" do
    value :Dummy3, 0
    value :UNKNOWN, 1
    value :QNAME, 2
    value :CLIENTIP, 3
    value :RESPONSEIP, 4
    value :NSDNAME, 5
    value :NSIP, 6
  end
end

PBDNSMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("PBDNSMessage").msgclass
PBDNSMessage::DNSQuestion = Google::Protobuf::DescriptorPool.generated_pool.lookup("PBDNSMessage.DNSQuestion").msgclass
PBDNSMessage::DNSResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("PBDNSMessage.DNSResponse").msgclass
PBDNSMessage::DNSResponse::DNSRR = Google::Protobuf::DescriptorPool.generated_pool.lookup("PBDNSMessage.DNSResponse.DNSRR").msgclass
PBDNSMessage::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("PBDNSMessage.Type").enummodule
PBDNSMessage::SocketFamily = Google::Protobuf::DescriptorPool.generated_pool.lookup("PBDNSMessage.SocketFamily").enummodule
PBDNSMessage::SocketProtocol = Google::Protobuf::DescriptorPool.generated_pool.lookup("PBDNSMessage.SocketProtocol").enummodule
PBDNSMessage::PolicyType = Google::Protobuf::DescriptorPool.generated_pool.lookup("PBDNSMessage.PolicyType").enummodule
