# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto3

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "RepeatedEvent" do
    optional :id, :string, 1
    optional :msg, :string, 2
  end
  add_message "RepeatedEvents" do
    repeated :repeated_events, :message, 1, "RepeatedEvent"
  end
end

Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("RepeatedEvent").msgclass
Events = Google::Protobuf::DescriptorPool.generated_pool.lookup("RepeatedEvents").msgclass
