# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TestMessage.proto3

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "com.foo.bar.IntegerTestMessage" do
    optional :response_time, :int64, 1
  end
end

module Com
  module Bla
    module Bla
      module Bla
        TestMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("com.foo.bar.IntegerTestMessage").msgclass
      end
    end
  end
end
