# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messageB.proto3

require 'google/protobuf'

require 'header/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "B.MessageB" do
    optional :name, :string, 1
    optional :header, :message, 2, "Header"
  end
end

module B
  MessageB = Google::Protobuf::DescriptorPool.generated_pool.lookup("B.MessageB").msgclass
end
