# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PhoneDirectory.proto

begin; require 'google/protobuf'; rescue LoadError; end

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("PhoneDirectory.proto", :syntax => :proto3) do
    add_message "company.communication.directories.PhoneDirectory" do
      repeated :contacts, :message, 1, "company.communication.directories.Contact"
      optional :last_updated_timestamp, :int32, 2
      oneof :scope do
        optional :internal, :bool, 3
        optional :external, :bool, 4
      end
    end
    add_message "company.communication.directories.Contact" do
      optional :name, :string, 1
      map :phone_numbers, :string, :int32, 2
      optional :address, :string, 3
      optional :fax, :int32, 4
      oneof :prefered_contact do
        optional :prefered_email, :string, 5
        optional :prefered_fax, :int32, 6
        optional :prefered_phone, :int32, 7
      end
    end
  end
end

module Company
  module Communication
    module Directories
      PhoneDirectory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("company.communication.directories.PhoneDirectory").msgclass
      Contact = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("company.communication.directories.Contact").msgclass
    end
  end
end
