# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResultList.proto

begin; require 'google/protobuf'; rescue LoadError; end

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ResultList.proto", :syntax => :proto3) do
    add_message "ProtoResultListComposerRequest" do
      repeated :metadata, :string, 1
      optional :page_number, :int32, 2
      optional :results_per_page, :int32, 3
      optional :result_list_composition_criteria, :message, 4, "ProtoResultListCompositionCriteria"
    end
    add_message "ProtoResultListCompositionCriteria" do
      optional :sort_criterion, :string, 1
      oneof :accommodation_id do
        optional :top_accommodation_id, :uint32, 2
        optional :recommend_similar_accommodation_id, :uint32, 3
      end
    end
  end
end

ProtoResultListComposerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProtoResultListComposerRequest").msgclass
ProtoResultListCompositionCriteria = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProtoResultListCompositionCriteria").msgclass
