# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello/world/AkamaiRum.proto

begin; require 'google/protobuf'; rescue LoadError; end

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hello.logging.ProtoHeader3" do
    optional :unix_timestamp, :int64, 1
    optional :sender_id, :string, 2
  end
end

module Hello
  module Logging
    ProtoHeader3 = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.logging.ProtoHeader3").msgclass
  end
end


Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hello.world.ProtoFun" do
    optional :header, :message, 1, "hello.logging.ProtoHeader3"
    optional :locale, :string, 2
    optional :user_agent, :message, 3, "hello.world.ProtoFun.Useragent"
    optional :geo, :message, 4, "hello.world.ProtoFun.Geo"
  end

  add_message "hello.world.ProtoFun.Useragent" do
    optional :browser_name, :string, 1
    optional :major, :float, 2
  end

  add_message "hello.world.ProtoFun.Geo" do
    optional :position, :message, 1, "hello.world.ProtoFun.Location"
    optional :city, :string, 2
    optional :isp, :string, 3
  end

  add_message "hello.world.ProtoFun.Location" do
    optional :x, :int32, 1
    optional :y, :int32, 2
  end
end

module Hello
  module World
    ProtoFun = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.world.ProtoFun").msgclass
    ProtoFun::Useragent = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.world.ProtoFun.Useragent").msgclass
    ProtoFun::Geo = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.world.ProtoFun.Geo").msgclass
    ProtoFun::Location = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.world.ProtoFun.Location").msgclass
  end
end
