# Generated by the protocol buffer compiler.  DO NOT EDIT!

begin; require 'google/protobuf'; rescue LoadError; end

begin; require 'google/protobuf/struct_pb'; rescue LoadError; end
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("RequestStruct.proto", :syntax => :proto3) do
    add_message "messages.SendJsonRequest" do
      optional :UserID, :string, 1
      optional :Details, :message, 2, "google.protobuf.Struct"
    end
    add_message "messages.SendJsonResponse" do
      optional :Response, :string, 1
    end
  end
end

module Messages
  SendJsonRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("messages.SendJsonRequest").msgclass
  SendJsonResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("messages.SendJsonResponse").msgclass
end