#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Grpc
  # forward declarations
  class Header < ::ProtocolBuffers::Message; end

  class Header < ::ProtocolBuffers::Message
    set_fully_qualified_name "grpc.Header"

    optional :string, :protocol, 1
  end

end
