# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header/header.proto3

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Header" do
    map :name, :string, :string, 3
  end
end

Header = Google::Protobuf::DescriptorPool.generated_pool.lookup("Header").msgclass
